---
- name: Deploy Terraform
  hosts: all
  gather_facts: False
  become: true

  tasks: 
    - name: Yum Install Packages
      yum: name='wget' state=latest

    - name: terraform install
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
        dest: /usr/bin
        remote_src: True

- name: Deploy Docker and kubectl
  hosts: all
  gather_facts: False
  become: true

  tasks: 
    - name: Install dependencies for Docker
      yum:
        name: yum-utils
        state: present

    # - name: Install Docker
    #   ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
    
    - name: docker installation
      command: amazon-linux-extras install docker -y

    - name: Add YUM repository for Kubernetes
      ansible.builtin.copy:
        src: kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo

    - name: Install Kubernetes
      yum: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl
    
...